name: Upload Extension as Artifact on Commit

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pack Extension
      run: chromium --pack-extension=${GITHUB_WORKSPACE}
    - name: Zip Extension
      run: zip -x *.crx -r lchs-go-extension.zip ${GITHUB_WORKSPACE}
    - run: ls
    - name: Upload Packed Extension
      uses: actions/upload-artifact@master
      with:
        name: crx
        path: ./*.crx
    - name: Upload Zipped Extension
      uses: actions/upload-artifact@master
      with:
        name: zip
        path: ./lchs-go-extension.zip
