name: Upload Extension as Artifact on PR

on:
  pull_request

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pack Extension
      run: chromium --pack-extension=$(pwd) && mv ../*.crx .
    - name: Upload Packed Extension
      uses: actions/upload-artifact@master
      with:
        name: crx
        path: ./*.crx
